apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik
  name: traefik
  namespace: traefik
spec:
  type: LoadBalancer
  ports:
  - name: web
    nodePort: 32177
    port: 80
    protocol: TCP
    targetPort: web
  - name: websecure
    nodePort: 30146
    port: 443
    protocol: TCP
    targetPort: websecure
  selector:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/name: traefik
  sessionAffinity: None
